title: "Mihir Madhaparia"
logo: /assets/images/"HeadshotPortrait.jpg"
description: "Personal website showcasing my education, work experience, and research."
theme: jekyll-theme-cayman
baseurl: "/"  # Leave this empty unless using a subdirectory
url: "mihirmadhaparia.github.io"  # Your GitHub Pages URL

# Navigation links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Education"
    url: "/education"
  - title: "Work Experience"
    url: "/work-experience"
  - title: "Projects"
    url: "/projects"
  - title: "Contact"
    url: "/contact"

# Plugins (optional)
plugins:
  - jekyll-seo-tag  # For SEO enhancements
  - jekyll-sitemap  # To generate a sitemap.xml
