title: "Mihir Madhaparia"
logo: /assets/images/"HeadshotPortrait.jpg"
description: "Personal website showcasing my education, work experience, and research."
theme: jekyll-theme-cayman
baseurl: "/"  # Leave this empty unless using a subdirectory
url: "mihirmadhaparia.github.io"  # Your GitHub Pages URL

# Plugins (optional)
plugins:
  - jekyll-seo-tag  # For SEO enhancements
  - jekyll-sitemap  # To generate a sitemap.xml
  - jekyll-markdown-filter # Liquid markdown understanding
